// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_inheritance.djinni

#import "DBSubObjcJavaInterfaceInheritance+Private.h"
#import "DBSubObjcJavaInterfaceInheritance.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class SubObjcJavaInterfaceInheritance::ObjcProxy final
: public ::testsuite::SubObjcJavaInterfaceInheritance
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::SubObjcJavaInterfaceInheritance;
public:
    using ObjcProxyBase::ObjcProxyBase;

    // SubObjcJavaInterfaceInheritance methods
    std::string sub_method() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() subMethod];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }

    // BaseObjcJavaInterfaceInheritance methods
    std::string base_method() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() baseMethod];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
    std::string override_method() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() overrideMethod];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto SubObjcJavaInterfaceInheritance::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto SubObjcJavaInterfaceInheritance::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
